language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

env:
  - DJANGO_VERSION=1.9.x
  - DJANGO_VERSION=1.8.x

install:
  - sudo apt-get update -y
  - sudo apt-get install graphicsmagick libjpeg-dev
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install "coveralls==1.0" coverage
  - coverage report
  - coveralls
